#!/usr/bin/env bash
# package.sh — build the shippable mod artifact. The ONLY producer of mod files.
#
#   ./dev/package.sh              build/  ->  mod tree + distribution archives + manifest
#   ./dev/package.sh --clean      remove build/
#
# Nothing in this repo copies a file into a running game or a Workshop directory.
# Everything the server or a client needs is produced here, from the repo, from
# mod/mod.json. That is deliberate: the artifact a tester mounts and the artifact a
# player downloads are the same bytes, so packaging cannot be "fixed later".
#
# Outputs
#   build/mod/                                  the mod tree (what gets zipped)
#   build/dist/<name>-<version>.zip             human-readable release archive
#   build/dist/m<hexId>_<version>.zip           the name the engine's backup-server
#                                               protocol requests (WorkshopBackup
#                                               check_path / make_key: 'm%x_%d.zip')
#   build/dist/manifest.json                    version, id, hash, file list
#
# Version is semantic (mod/mod.json -> version). Pre-1.0 is intentional: nothing here
# has been confirmed working in game yet. The distribution filename uses
# version=0 while the item has no PublishedFileId, because that is what the engine
# asked for when it looked the mod up ("mod [999000001] with version 0"). Once the
# item is published, publishedFileId replaces modId and Steam's time_updated replaces
# the 0, and this script is the only place either is read.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
META="$REPO/mod/mod.json"
SRC="$REPO/source/lua/shine/extensions"
BUILD="$REPO/build"
MODDIR="$BUILD/mod"
DIST="$BUILD/dist"

[[ -f "$META" ]] || { echo "[package] missing $META" >&2; exit 1; }

if [[ "${1:-}" == "--clean" ]]; then
  rm -rf "$BUILD"
  echo "[package] removed $BUILD"
  exit 0
fi

[[ -d "$SRC" ]] || { echo "[package] missing source: $SRC" >&2; exit 1; }

eval "$(python3 -c "
import json
m = json.load(open('$META'))
name, ver, mid = m['name'], m['version'], m.get('publishedFileId') or m['modId']
print(f'NAME={name}'); print(f'VERSION={ver}')
print(f'MOD_ID={mid}'); print(f'HEX_ID={mid:x}')
print(f'DIST_VERSION={0 if m.get(\"publishedFileId\") is None else 1}')
print(f'PRIORITY={m.get(\"entryPriority\", 40)}')
print(f'PRE_PUBLISHED={1 if m.get(\"publishedFileId\") is None else 0}')
")"

# A semver string cannot contain the characters that would break a path, but check
# anyway: a typo here silently produces an artifact nobody can install.
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] || {
  echo "[package] version '$VERSION' is not semver (e.g. 0.0.1 or 0.1.0-rc1)" >&2; exit 1; }

rm -rf "$BUILD"
mkdir -p "$MODDIR/lua/entry" "$DIST"

# ---------------------------------------------------------------- the entry file
# Executed as Lua; must set a global modEntry. The entry FILENAME is the mod name
# (core/lua/ModLoader.lua:227-229). No Client/Server/Shared scripts are declared:
# Shine is the host and loads our extensions through its own merged-VFS scan
# (MODDING-CASES.md §2b). Priority is declared because it governs load order against
# Shine (50) - HIGHER loads first (ModLoader.lua:236-242).
cat > "$MODDIR/lua/entry/$NAME.entry" <<EOF
-- Generated by dev/package.sh from mod/mod.json. Do not edit: edit the source and
-- re-run. version $VERSION
modEntry = {
    Priority = $PRIORITY
}
EOF

# ---------------------------------------------------------------- the extensions
mkdir -p "$MODDIR/lua/shine/extensions"
cp -r "$SRC/." "$MODDIR/lua/shine/extensions/"

# Optional workshop tile
[[ -f "$REPO/mod/preview.jpg" ]] && cp "$REPO/mod/preview.jpg" "$MODDIR/preview.jpg"

# ---------------------------------------------------------------- archives
# Deterministic zip: fixed timestamp and sorted members, so the same inputs always
# produce the same bytes. Without this, "rebuild the artifact" changes the hash and
# the version-skew problems documented in WorkshopBackup's README become invisible.
python3 - "$MODDIR" "$DIST/$NAME-$VERSION.zip" "$DIST/m${HEX_ID}_${DIST_VERSION}.zip" <<'PY'
import os, sys, zipfile
src, out_a, out_b = sys.argv[1:4]
files = sorted(os.path.relpath(os.path.join(r, f), src)
               for r, _, fs in os.walk(src) for f in fs)
for out in (out_a, out_b):
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for name in files:
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.external_attr = 0o644 << 16
            with open(os.path.join(src, name), "rb") as fh:
                z.writestr(info, fh.read())
print(f"[package] {len(files)} files per archive")
PY

MOD_HASH=$(cd "$MODDIR" && find . -type f | sort | xargs -r md5sum | md5sum | cut -c1-8)
ZIP_HASH=$(md5sum "$DIST/$NAME-$VERSION.zip" | cut -c1-8)

python3 - "$DIST/manifest.json" "$NAME" "$VERSION" "$MOD_ID" "$HEX_ID" "$MOD_HASH" "$ZIP_HASH" "$PRE_PUBLISHED" <<'PY'
import json, sys, os
out, name, version, mod_id, hex_id, mod_hash, zip_hash, pre = sys.argv[1:9]
files = sorted(os.path.relpath(os.path.join(r, f), os.path.join(os.path.dirname(out), "..", "mod"))
               for r, _, fs in os.walk(os.path.join(os.path.dirname(out), "..", "mod")) for f in fs)
json.dump({
    "name": name, "version": version,
    "modId": int(mod_id), "hexId": hex_id,
    "published": pre != "1",
    "modTreeHash": mod_hash, "archiveHash": zip_hash,
    "archives": [f"{name}-{version}.zip", f"m{hex_id}_{0 if pre == '1' else 1}.zip"],
    "files": files,
}, open(out, "w"), indent=2)
print(f"[package] manifest -> {out}")
PY

echo "[package] mod '$NAME' v$VERSION id=$MOD_ID (hex $HEX_ID, dist version $DIST_VERSION)"
echo "[package] tree [$MOD_HASH]  archive [$ZIP_HASH]"
ls -1 "$DIST" | sed 's/^/[package]   /'
