#!/usr/bin/env bash
# paths.sh — the ONE definition of every path this project uses.
#
# Sourced by dev/*.sh. Nothing else may hard-code a location. The reason is not
# tidiness: paths were scattered across D:\games during early sessions (an abandoned
# config dump holding live tokens, a hyphenated dir the engine could not parse, a
# "test" directory that had quietly become the project's permanent home), and the
# human had to ask what all of it was. One file answers that question permanently.
#
# Layout
#   <repo> D:\projects\ns-seeding-horde-mode   (WSL: /mnt/d/projects/...)
#       mod.settings                LaunchPad project file (name, dirs, tags)
#       source/                     the mod tree - hand-written, version-controlled
#       output/                     generated by package.sh; what LaunchPad publishes
#       dist/<version>/             generated release archives + manifest
#   D:\games\horde\server\        runtime state only, nothing authored here
#       cfg\                        DEV server config   (disposable, generated)
#       mods\                       DEV mod storage     (isolated via -modstorage)
#   D:\games\ns2srv\cfg             LIVE server config  - ARIAN'S, never written
#   D:\games\ns2-server\            engine + dedicated server (steamcmd app 4940)
#
# Two constraints encoded below, both learned expensively:
#   1. No hyphens. The launch-argument parser's token break-set is `-+;`, so a hyphen
#      inside -config_path truncates the value (MODDING.md fact 17).
#   2. Nothing under steamapps is ever a write target (dev/STANDARDS.md).

# --- root --------------------------------------------------------------------
HORDE_ROOT_WIN='D:\games\horde'
HORDE_ROOT_WSL='/mnt/d/games/horde'

# --- the project itself ------------------------------------------------------
# The repo IS the LaunchPad project: mod.settings declares source_dir and output_dir, both
# relative to the project folder. Note the file says "source"/"output" WITHOUT a trailing
# slash — LaunchPad rewrote it that way on first open, and a comment here used to claim the
# opposite. Nothing parses those two keys (paths.sh derives its own paths); they exist for
# LaunchPad, so LaunchPad's spelling is the one recorded.
# There is deliberately no second copy of the mod under D:\games - an earlier layout kept
# repo/source, a build tree, a project source and a project output: four copies of the same
# files with no answer to "which one is real".
_REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MOD_NAME=$(sed -n 's/^name[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$_REPO_DIR/mod.settings")
LAUNCHPAD_PROJECT_WIN="$(wslpath -w "$_REPO_DIR" 2>/dev/null || echo "$_REPO_DIR")"
OUTPUT_WSL="$_REPO_DIR/output"
DIST_WSL="$_REPO_DIR/dist"

# Windows form of the repo, for telling LaunchPad (a Windows app) where the project is.
# This is why the repo lives on D:\ : wslpath resolves a WSL-home repo to
# \\wsl.localhost\Ubuntu\..., which LaunchPad mangles to C:\wsl.localhost\... and then
# correctly reports that the output directory is empty.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_WIN="$(wslpath -w "$REPO_DIR" 2>/dev/null || echo "$REPO_DIR")"
REPO_SETTINGS_WIN="$REPO_WIN\\mod.settings"


# --- dev server instance (disposable: delete it and deploy.sh rebuilds it) ----
DEV_CFG_WIN="$HORDE_ROOT_WIN\\server\\cfg"
DEV_CFG_WSL="$HORDE_ROOT_WSL/server/cfg"
DEV_MODS_WIN="$HORDE_ROOT_WIN\\server\\mods"
DEV_MODS_WSL="$HORDE_ROOT_WSL/server/mods"
DEV_LOG_DIR="$DEV_CFG_WSL/shine/logs"

# --- the user's live server: read-only ---------------------------------------
LIVE_CFG_WIN='D:\games\ns2srv\cfg'
LIVE_CFG_WSL='/mnt/d/games/ns2srv/cfg'

# --- engine and shared runtime state -----------------------------------------
ENGINE_WIN='D:\games\ns2-server'
ENGINE_WSL='/mnt/d/games/ns2-server'
# Engine logs, crash dumps and the default mod store ignore -config_path and are
# shared by every instance on this box (MODDING.md fact 15).
APPDATA_NS2_WSL="/mnt/c/Users/aria/AppData/Roaming/Natural Selection 2"
LOG_WSL="${NS2_LOG:-$APPDATA_NS2_WSL/log-Server.txt}"
CLIENT_LOG_WSL="$APPDATA_NS2_WSL/log.txt"
DUMPLOG_WSL="$APPDATA_NS2_WSL/dumps/dumplog.txt"

# Workshop copies of Shine. Repair targets for --clean, NEVER write targets.
SERVER_SHINE_EXT="$APPDATA_NS2_WSL/workshop/content/4920/117887554/lua/shine/extensions"
CLIENT_SHINE_EXT="/mnt/c/Program Files (x86)/Steam/steamapps/workshop/content/4920/117887554/lua/shine/extensions"

# --- ports -------------------------------------------------------------------
LIVE_PORT=27015          # engine default; a second port (27016) also opens
DEV_PORT=27025           # paired allocation: DEV takes P and P+1
MODSERVER_PORT=27020     # UWE's WorkshopBackup default for the backup protocol

# --- guards ------------------------------------------------------------------
# Fail fast, from one place, on the two rules above.
paths_validate() {
  local p
  for p in "$DEV_CFG_WIN" "$DEV_MODS_WIN"; do
    case "$p" in
      *-*) echo "[paths] FAIL - path contains a hyphen, which the engine's argument parser truncates: $p" >&2; return 1 ;;
    esac
  done
  for p in "$DEV_CFG_WSL" "$DEV_MODS_WSL"; do
    case "$p" in
      */steamapps/*|*"/Program Files (x86)/Steam"*)
        echo "[paths] FAIL - a project write path is inside Steam-managed content: $p" >&2
        echo "[paths]        see dev/STANDARDS.md - this breaks the real game's mod consistency" >&2
        return 1 ;;
    esac
  done
  return 0
}

# Where a version's artifact lives. One function so no script invents its own scheme.
dist_dir_for() {          # $1 = version
  echo "$DIST_WSL/$1"
}
dist_dir_for_win() {      # $1 = version
  echo "$DIST_WIN\\$1"
}

# The name the backup protocol addresses a mod by: m<hex id>_<workshop version>.zip, where the
# version is Steam's (0 until published), not our semver — same rule dev/package.sh writes with.
# ONE authority, because "the first m*_*.zip in dist/" is not this file: on 2026-09-25 it
# returned the pre-publication placeholder (999000001 -> m3b8b87c1_0.zip), which sorts before
# ours, and both the server's own fetch check and a delivery probe reported HTTP 200 about it.
# A passing check against the wrong artifact is worse than a failing one.
mod_archive_name() {
  python3 - "$REPO_DIR/mod/mod.json" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))
mid = m.get("publishedFileId") or m["modId"]
version = 0 if not m.get("publishedFileId") else (m.get("workshopVersion") or 0)
print(f"m{mid:x}_{version}.zip")
PY
}

# --- the player's game install -------------------------------------------------
# Read-only to us (dev/STANDARDS.md). Defined here so no script hard-codes it when
# telling a human where LaunchPad lives.
CLIENT_INSTALL_WIN='C:\Program Files (x86)\Steam\steamapps\common\Natural Selection 2'
CLIENT_INSTALL_WSL='/mnt/c/Program Files (x86)/Steam/steamapps/common/Natural Selection 2'
LAUNCHPAD_WIN="$CLIENT_INSTALL_WIN\\LaunchPad.exe"
